### ISSUE TITLE
Does getTimeline pull all the tweets?

### ISSUE THREAD

**Issue by mobcdi** [SMAPPNYU/smappR#1]
If the total number of tweets by a user is less than the twitter API limit of 3200. does getTimeline get ALL of them  or just a portion of tweets?

**Comment by pablobarbera** [comment]
It will return all of them, yes. I updated the documentation to make sure this is clear. Thanks!

**Comment by mobcdi** [comment]
Sorry I think I didn't explain my question correctly. Is it possible with your package to get all the tweets for a user from their 1st tweet to the most recent using getTimeline even if the account has been open for a number of years?

**Comment by pablobarbera** [comment]
Yes, as long as they are less than 3,200 tweets. For example, my account (@p_barbera) was created in 2007 and has ~1,400 tweets, and I'm able to get all of them with getTimeline.

**Comment by mobcdi** [comment]
Does it involve polling the twitter API and building up a database of tweets over time?
