### ISSUE TITLE
Error while installing smappR package. Kindly fix this issue ASAP

### ISSUE THREAD

**Issue by solomonchristyab** [SMAPPNYU/smappR#10]
When I tried to install smappR in my windows machine, it showed:

```
> require(devtools)
> install_github("smappR", "SMAPPNYU")
Downloading GitHub repo SMAPPNYU/smappR@master
from URL https://api.github.com/repos/SMAPPNYU/smappR/zipball/master
Error in utils::packageVersion("curl") : package ‘curl’ not found
In addition: Warning message:
Username parameter is deprecated. Please use SMAPPNYU/smappR 
```

I couldn't use getTimeline() because of this issue.

Kindly help me fixing it ASAP.
Thanks in advance!

**Comment by pablobarbera** [comment]
The error message already points out the problem: you need to install the "curl" package first.

**Comment by solomonchristyab** [comment]
Sir! I already installed curl and RCurl packages. I ran the updated version of curl which is curl_0.9.6. Problem has not been sorted out even after that @pablobarbera

**Comment by solomonchristyab** [comment]
Error has been solved! Thanks @pablobarbera
