### ISSUE TITLE
Potential improvement for getTimeline

### ISSUE THREAD

**Issue by kmunger** [SMAPPNYU/smappR#12]
Hey Pablo,

Not sure if you still use getTimeline (I do!) but I think I've found a solution to a problem that's been bugging me on Windows for years.

When I try to read in tweets from a json file created with getTimeline, I always get caught up with non-ascii characters. I decided to look into this function, and it turns out that if I set useBytes = T, I'm able to read in the tweets from the json files no problem. 

I'm not sure if there's a reason you'd want to leave useBytes = F ; if not, you might consider changing the function.

**Comment by pablobarbera** [comment]
Thanks! Based on my tests, this doesn't affect how tweets are downloaded in my Mac, so if it fixes the issues on your end, I say let's switch to useBytes=TRUE. :-)
