### ISSUE TITLE
word frequency function

### ISSUE THREAD

**Issue by RodriguezGoldstein** [SMAPPNYU/smappR#4]
Thank you for this great package, there is problem on the word frequency function. On the new version of tm (0.6-2), when modifying R objects we need to use content_transformer() function, if not R I get this error (Error in enc2utf8(x) : argument is not a character vector). I just added the  content_transformer function to your code and it works fine.

```
myCorpus <- tm_map(myCorpus, content_transformer(function(x) iconv(enc2utf8(x), sub = "byte")))
myCorpus <- tm_map(myCorpus, content_transformer(tolower))
myCorpus <- tm_map(myCorpus, content_transformer(removeNumbers))
myCorpus <- tm_map(myCorpus, content_transformer(removeURL))
```

**Comment by pablobarbera** [comment]
Thanks a lot!
