### ISSUE TITLE
[Question] Lookup Users

### ISSUE THREAD

**Issue by nurandi** [SMAPPNYU/smappR#5]
Hi, thank you for creating a great package :)

I have more than 80k users retrieved using `getFollowers()`. What is the best way to get all those users data, since `getUsers()` is limited up to 100 users per request?

**Comment by pablobarbera** [comment]
Hi @nurandi and thanks for using our package!

I have added a new function (getUsersBatch) to download user data for more than 100 users, in data frame format. Note that it will only return a few user fields (id_str, screen_name, name, description, followers_count, statuses_count, friends_count, created_at, and location), but if you're interested in others, let me know!

**Comment by nurandi** [comment]
Awesome.. :+1: , thank you, @pablobarbera :)

I also need other fields i.e. `time_zone`, `lang` and `status` (`id_str`, `created_at`, `text`).  Would you mind adding these addition fields? Thank you

**Comment by pablobarbera** [comment]
@nurandi done! :)
